version: '2'
services:
  web:
    build: .
    depends_on:
      - mydb
    ports:
      - "8069:8069"
    environment:
    - HOST=mydb
    - USER=odoo
    - PASSWORD=myodoo
    command: ./odoo-bin -i base -d test --addons-path=/opt/odoo/addons
    volumes:
      - ./odoo.conf:/etc/odoo/odoo.conf:ro
  mydb:
    image: postgres:10
    environment:
      - POSTGRES_DB=rdb
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
